version: 3

tasks:
  pretty:
    aliases: [p, format, fmt]
    desc: Uses the Prettier CLI tool to format the codebase.
    cmds: [prettier --write .]

  push:
    aliases: [dd]
    desc: Push any git changes and tags to the remote repository.
    deps: ['build']
    cmds: [git push, git push --tags]

